hardcode audio quality for extremely limited platforms
libsndfile/libsamplerate pull request #127
Opened 2020-11-19 14:53 UTC by jerpelea

Many NuttX boards have limited rerources and will have to use
compile time quality options to reduce resource usage

Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

2020-11-20 10:29 UTC, jerpelea commented
@evpobr

2020-11-21 06:36 UTC, evpobr requested changes
It's a good idea, but the pull request needs to be improved. We will probably need a set of options for the build systems so that we can select the available converters, and this should be done for both Autotools and CMake.

2020-11-21 06:58 UTC, evpobr commented
Look at #128.

2020-11-23 07:59 UTC, jerpelea commented
@evpobr I can add the options for the build system for other OSes. In our case they are set in Kconfig for NuttX OS

2020-11-23 09:12 UTC, evpobr commented
First we need to add ifdefs to libsamplerate's code and its buildsystems. I've started work in #128 but i have no time to complete it, i'll probably be very busy for the rest of the year. You can try if you wish.

2020-11-23 09:26 UTC, jerpelea commented
@evpobr  it is alreaady done. please check my patch

2020-11-23 09:52 UTC, evpobr requested changes
There are build errors in Travis CI tests.

2020-11-23 10:23 UTC, jerpelea commented
@evpobr local build and test was ok. I will fix the CI ones

2020-11-24 06:00 UTC, jerpelea commented
@evpobr no more errors. please review

2020-11-24 07:08 UTC, evpobr requested changes
Sinc converter is disabled for Autotools build system, need options to set it on/off, enabled by default.

2020-11-24 07:13 UTC, jerpelea commented
where should those options be located for autotools?

2020-11-24 07:18 UTC, evpobr commented
This could help: https://autotools.io/autoconf/arguments.html.

2020-11-24 09:43 UTC, jerpelea commented
@evpobr done. It seems to work. Please review

2020-11-24 10:48 UTC, evpobr requested changes
Very good work, @jerpelea! After cleanup i've mentioned in my review, we will ask review from @SoapGentoo, i need to know that Autotools code is correct. And then i will merge it.

2020-11-24 10:48 UTC, evpobr commented on CMakeLists.txt
> +option(LIBSAMPLERATE_WITH_SINC_FAST_CONVERTER "Enable Fastest Sinc Interpolator converter" ON)
Maybe it is better to rename options to `LIBSAMPLERATE_ENABLE_SINC_ХХХ`? These names are more like the names of Autotools options. In addition, by tradition, Autotools` WITH ' means external dependencies.

2020-11-24 10:48 UTC, evpobr commented on src/samplerate.c
> +#ifdef WITH_SINC_BEST_CONVERTER
And rename defines to something like `ENABLE_SINC_BEST_CONVERTER`.

2020-11-24 10:53 UTC, SoapGentoo requested changes

2020-11-24 10:53 UTC, SoapGentoo commented on configure.ac
> +		dnl explicitly passed --enable-sinc-fast, hence error out loud and clearly
remove (just the comment)

2020-11-24 10:53 UTC, SoapGentoo commented on configure.ac
> +		dnl explicitly passed --enable-sinc-medium, hence error out loud and clearly
remove

2020-11-24 10:53 UTC, SoapGentoo commented on configure.ac
> +		dnl explicitly passed --enable-sinc-best, hence error out loud and clearly
remove

2020-11-24 10:53 UTC, SoapGentoo commented on src/src_sinc.c
> +
spurious whitespace change

2020-11-24 14:26 UTC, jerpelea commented on CMakeLists.txt
> +option(LIBSAMPLERATE_WITH_SINC_FAST_CONVERTER "Enable Fastest Sinc Interpolator converter" ON)
done

2020-11-24 14:27 UTC, jerpelea commented
@evpobr done

2020-11-24 14:52 UTC, SoapGentoo approved these changes

2020-11-24 15:32 UTC, evpobr approved these changes

2020-11-24 15:32 UTC, merged

2020-11-24 15:33 UTC, evpobr commented
Thanks @jerpelea!