INSTALL: Some more grammatical fixes are made.
libsndfile/libsamplerate pull request #165
Opened 2021-06-06 19:53 UTC by varikvalefor

On line 99, s/other location/another location/ is possible.  However, VARIK finds that s/other location/other locations/ is the most natural fix.

2021-06-06 19:53 UTC, varikvalefor commented
Ignore the old changes to README.md.

2021-06-07 15:42 UTC, evpobr commented
@SoapGentoo , my english is to bad :-)

2021-06-07 15:45 UTC, SoapGentoo requested changes

2021-06-07 15:45 UTC, SoapGentoo commented on INSTALL
> +Linux and other Unix-like systems, including Mac OS X. (For Windows,
```suggestion
Linux and other Unix-like systems, including macOS. (For Windows,
```

2021-06-19 15:15 UTC, closed without merging